### ISSUE TITLE
support PG13

### ISSUE THREAD

**Issue by sanderr** [inmanta/postgresql#225]
The current implementation only supports PG10. Since PG13 is the officially supported version for our products, it makes sense to support at least that version. Only one version needs to be supported, but parametrization would be even better.

A side effect is that the management orchestrator and all test orchestrators currenly use PG13. Ideally, these should be updated. If this requires additional work, a follow-up ticket should be created.

If recreating test orchestrators, make sure to update the lock values for pytest-inmanta-lsm

**Comment by Hugo-Inmanta** [comment]
Shelving this ticket for now as it turned out too hard for me.
- I have the beginnings  of an implementation on this branch: https://github.com/inmanta/postgresql/pull/239, but it might be easier to start afresh.
- Here is a related slack discussion about the testing that should be done: https://inmanta.slack.com/archives/CKRF0C8R3/p1675245443076869?thread_ts=1675152308.368499&cid=CKRF0C8R3
